### ISSUE TITLE
Error requesting access to IG

### ISSUE THREAD

**Issue by seanmcilvenna** [lantanagroup/trifolia#10]
> I'm getting an error when I try an request view access for these Export Schematrons:
> "Consolidated CDA Templates for Clinical Notes (US Realm) DSTU R1.1"
> "Consolidated CDA Templates for Clinical Notes (US Realm) DSTU R2.1"

**Comment by seanmcilvenna** [comment]
I've determined that this is not an issue with code. This appears to be an issue with our production installation of trifolia at https://trifolia.lantanagroup.com. Trifolia is unable to connect to our configured mail server. I have asked @michael-misiaszek to investigate this further and determine why our mail server is not accepting connections from Trifolia.

**Comment by michael-misiaszek** [comment]
The issue has been resolved. The problem was due to this server being blocked by the firewall for outbound SMTP.
