### ISSUE TITLE
Constraints appearing in red when re-expanding constraints

### ISSUE THREAD

**Issue by minigrrl** [lantanagroup/trifolia#12]
I'm getting this fairly often in templates I'm editing (wonder if it's related to the constraints out of order bug?).  See screenshot.  I don't think it actaully affects anything, because if I go out of the template and back in the problem goes away...  

I don't know how to reproduce, it seems to randomly (though I'm sure it's not random!) pop up!

![image](https://cloud.githubusercontent.com/assets/14354654/20049027/3ae7abc0-a50c-11e6-89c7-fddd086c8ea9.png)

**Comment by minigrrl** [comment]
I was wrong, I can reproduce.  I can get it to repeat a new set of attributes by using the arrow next to value and opening and closing the list of attributes.  See new screenshot.

![image](https://cloud.githubusercontent.com/assets/14354654/20049135/e9ebad4c-a50c-11e6-9801-2e8e97271ca4.png)

**Comment by seanmcilvenna** [comment]
Ok. I have seen this once before recently as well.
This is definitely an issue I want to get resolved.
@meenaxigosai  or @wendywise can you make sure this issue is on the next JIRA sprint?

**Comment by minigrrl** [comment]
It’s been driving me crazy for years.  It just never seemed priority because it’s so small…

**Comment by minigrrl** [comment]
I don’t suppose that, while you are in there you could default, on the value sets page, the Create as appendix to NO rather than the current YES, as we never create value sets as an appendix.  There is a jira ticket for this…

https://jira.lantanagroup.com/browse/TRIF-732

Though it looks like it was fixed at some point but it must have reverted!

**Comment by meenaxigosai** [comment]
This issue has been tested and resolvedin the Trifolia development environment.  The fix will be deployed to production with the next release.   JIRA reference # TRIF-1158

**Comment by meenaxigosai** [comment]
This issue was tested in https://trifolia-dev.lantanagroup.com on January 31st, 2017 and closed as part of https://lantana.atlassian.net/browse/TRIF-1158, and released to production in v4.40 on May 26, 2017.
