### ISSUE TITLE
Unable to create a login to https://trifolia.lantanagroup.com/ or download trifolia application

### ISSUE THREAD

**Issue by Mattius604** [lantanagroup/trifolia#23]
I have been trying to create a login for the site https://trifolia.lantanagroup.com/ in order to download Trifolia. When I try to create an account, I enter a username and password, and the screen refreshes with no acknowledgment, and no confirmation email is sent. When I try to log in with those credentials, the login page just refreshes, no errors.

I'm hoping an admin is out there, and can check that the user creation process is working.

**Comment by meenaxigosai** [comment]
Hello,

I am a Trifolia Admin.  Could you please provide me with the e-mail address you were using when you tried to create the new account, and I will check the Trifolia Users page to determine if the account was created.

Thank you,

Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545

**Comment by Mattius604** [comment]
mattius604@gmail.com

**Comment by meenaxigosai** [comment]
Hello,

I have confirmed that your account as been created in the Auth0 system, but the e-mail account mattius604@gmail.com  is in (pending) state.  I suspect that the reason you are unable to log into Trifolia is that the account is pending e-mail verification.

Could you please log into your mattius604@gmail.com account and check to see if you have an e-mail verification or a password change e-mail in your inbox from <no-reply@auth0user.net>.  The e-mail may have gone into you Junk/Spam folder.

Thank you,

Meenaxi

Thank you,

**Comment by Mattius604** [comment]
Neither the create user, or password reset sent an email to this account. I check the junk folders, nothing there.

**Comment by meenaxigosai** [comment]
Hello,

Thank you for your patience and willingness to work with our team as we attempt to resolve the issue you have reported.

I have manually verified the Auth0 e-mail account.  Please try to login to Trifolia and let me know if you have any problems.

Best Regards,

Meenaxi

**Comment by Mattius604** [comment]
Ok I can log in.

 

Now where is the download link for the tool? I still cant find that link…

**Comment by seanmcilvenna** [comment]
The tool itself is a web-based application. There is no "download link". All of the application's functionality is available to you via the website after you have logged in. I suggest that you review the help documentation under the "Help" menu. There is quite a bit of information in there that might help you with the learning curve.

**Comment by seanmcilvenna** [comment]
Have not heard back from you in over two weeks. If this is still an issue, please let us know and we can re-open it. Until then, going to close this issue out.
