### ISSUE TITLE
(Enhancement) Add relationships tab to edit page

### ISSUE THREAD

**Issue by minigrrl** [lantanagroup/trifolia#25]
Add relationships tab to edit page so that one can see the relationships of a template while editing it.

**Comment by meenaxigosai** [comment]
TRIF-1165

**Comment by meenaxigosai** [comment]
Hello @minigrrl 

We are moving from GITHUB to JIRA Support Desk. Therefore, I have created JIRA ticket TRIF-1355 to track this issue and will close this GITHUB ticket out.

Regards,

Meenaxi Gosai
