### ISSUE TITLE
Update New DDL to include Upgrade DDL

### ISSUE THREAD

**Issue by qagwaai** [lantanagroup/trifolia#27]
Can you create a new 4.2 DDL with the changes included in the Upgrade scripts?  isChoice on template_constraint is an example.

**Comment by seanmcilvenna** [comment]
Ah yes, I failed to update the "new" database script when I did the last update; was a little rushed. I will do that now.

**Comment by seanmcilvenna** [comment]
Ok. I have pushed an export of the database creation script for 4.3.0 to master. I did not test creating a new database, so if you could test that for me and make sure it works as desired, that would be greatly helpful. Assuming it works, please close out this ticket.
