### ISSUE TITLE
FHIR StructureDefintion output incorrect: profile needs to be targetProfile

### ISSUE THREAD

**Issue by rgeimer** [lantanagroup/trifolia#29]
Current output looks like this:

`        <type>
            <code value="Reference" />
            <profile value="http://hl7.org/fhir/us/core/StructureDefinition/us-core-allergyintolerance" />
        </type>
`

Needs to look like this instead:
`        <type>
            <code value="Reference" />
            <targetProfile value="http://hl7.org/fhir/us/core/StructureDefinition/us-core-allergyintolerance" />
        </type>`

...but always check against the latest FHIR schemas before calling this done in case the name changes again. 

Also, this only applies when code = Reference, not for things like code = Extension. 

TRIF-1157

**Comment by seanmcilvenna** [comment]
This issue has been resolved in the development environment. It will be included in the 4.5.0 release.

**Comment by seanmcilvenna** [comment]
Trifolia 4.5.0 has been released. This fix is included in the release. Please re-open the ticket if you encounter further problems related to this issue.
