### ISSUE TITLE
Nothing listed when browsing IGs and template/profiles

### ISSUE THREAD

**Issue by p9g** [lantanagroup/trifolia#3]
Was working yesterday with 4.1.0, today with 4.2.0 nothing is listed.  I can see things under Terminology, but nothing under IGs or templates/profiles.  The request access form does not work under IG.

**Comment by seanmcilvenna** [comment]
Hi Paul, I'm looking into this now. Can you confirm one of the IGs you had access to before, that you do not now?

**Comment by p9g** [comment]
For IG, I think I was looking at a QRDA Category I IG, probably others.

Under Browse Templates/Profiles, I saw a bunch and could enter a Name 
and OID to filter, for example, with Identifier set to 
"2.16.840.1.11.113883.10.20.22.1.1" and Name set to "Realm", I would get 
4 results with the left three columns (Name, Identifier, Implementation 
Guide) as follows

Name
US Realm Header
US Realm Header (V2)
US Realm Header (V3)
US Realm Header (V3)

Identifier
urn:oid:2.16.840.1.11.113883.10.20.22.1.1
urn:hl7ii:2.16.840.1.11.113883.10.20.22.1.1:2014-06-09
urn:hl7ii:2.16.840.1.11.113883.10.20.22.1.1:2015-08-01
urn:hl7ii:2.16.840.1.11.113883.10.20.22.1.1:2015-11-02

IG
Consolidation
Consolidation V2
Consolidation V3
Initial Public Health Case Report

Paul

**Comment by seanmcilvenna** [comment]
Hi Paul, thanks for your patience while I figure this out. I have identified the problem, and believe I have fixed it. Please confirm if the problem is solved for you now, and close the issue if it is.

**Comment by p9g** [comment]
Seems to be fixed, thanks.
