### ISSUE TITLE
Re: Trifolia: Request to access Public Health Case Report Release 2

### ISSUE THREAD

**Issue by michael-misiaszek** [lantanagroup/trifolia#30]
I am not able to login through HL7 and am unable to give the user
permissions. can you do it for me?

thanks,

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

On Mon, Dec 5, 2016 at 12:13 PM, <it-support@lantanagroup.com> wrote:

> User Keith Boone (kwboone@gmail.com) has requested access to Public
> Health Case Report Release 2 on 12/5/2016 @ 3:13 PM
> The user has requested view permissions.
>
> Message from user: None
>
> Use this link to add them to the implementation guide:
> https://trifolia.lantanagroup.com/IGManagement/Edit/2213
>
>

**Comment by meenaxigosai** [comment]
From: Meenaxi Gosai
Sent: December 9, 2016 10:07 AM
To: kwboone@gmail.com
Cc: ehaas@healthedatainc.com; Sean P. McIlvenna
Subject: Re: Trifolia: Request to access Public Health Case Report Release 2 (#30)
 
Hello Keith,

I have granted you view permissions to the Public Health Case Report Release 2 implementation guide.

Please let Lantana know if you require any further assistance.

Best Regards,

Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
 
www.lantanagroup.com
Blog | Twitter | LinkedIn
