### ISSUE TITLE
RE: Trifolia: Request to access Consolidation V3

### ISSUE THREAD

**Issue by michael-misiaszek** [lantanagroup/trifolia#31]
Adding correct email!

Ignore gmelton@umn.edu

----Original Message----
From: Brett Marquard
Sent: Thursday, November 17, 2016 8:47 AM
To: 'Genevieve Melton-Meaux' <gmelton@umn.edu>
Cc: 'it-support@lantanagroup.com' <it-support@lantanagroup.com>
Subject: RE: Trifolia: Request to access Consolidation V3

I was able to add you as an individual...

Not sure if the 'HL7 group' permissions previously gave you access.

----Original Message----
From: it-support@lantanagroup.com it-support@lantanagroup.com
Sent: Wednesday, November 16, 2016 4:41 PM
To: Brett Marquard <brett@riverrockassociates.com>
Subject: Trifolia: Request to access Consolidation V3

User George Cole (george.cole@allscripts.com) has requested access to Consolidated CDA Templates for Clinical Notes (US Realm) DSTU R2.1 on 11/16/2016 @ 4:40 PM The user has requested view permissions.

Message from user: What happened to the HL7 credentials login - that used to allow me to see almost everything.....this apparently new account shows me virtually nothing.

Use this link to add them to the implementation guide: https://trifolia.lantanagroup.com/IGManagement/Edit/1198

I was able to add you as an individual...

Not sure if the 'HL7 group' permissions previously gave you access.

----Original Message----
From: it-support@lantanagroup.com it-support@lantanagroup.com
Sent: Wednesday, November 16, 2016 4:41 PM
To: Brett Marquard <brett@riverrockassociates.com>
Subject: Trifolia: Request to access Consolidation V3

User George Cole (george.cole@allscripts.com) has requested access to Consolidated CDA Templates for Clinical Notes (US Realm) DSTU R2.1 on 11/16/2016 @ 4:40 PM The user has requested view permissions.

Message from user: What happened to the HL7 credentials login - that used to allow me to see almost everything.....this apparently new account shows me virtually nothing.

Use this link to add them to the implementation guide: https://trifolia.lantanagroup.com/IGManagement/Edit/1198

**Comment by meenaxigosai** [comment]
Hello Brett,

I have checked in Trifolia and user George Cole (george.cole@allscripts.com) already has access to Consolidated CDA Templates for Clinical Notes (US Realm) DSTU R2.1.

Please clarify if you require more assistance in providing any other HL7 users access to resources they are working on.

Thank you,


Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
 
www.lantanagroup.com
Blog | Twitter | LinkedIn

**Comment by rgeimer** [comment]
No reply in over a month, so assuming this is resolved. Closing the ticket.
