### ISSUE TITLE
How do I add a new local codeSystem?

### ISSUE THREAD

**Issue by LisaRNelson** [lantanagroup/trifolia#33]
Right now the drop-down list for the code system is closed.  I can't seem to add a new codeSystem to the pick list. How do I get the code system I need added to the list?

I need ADVault, Inc. (http://advaultinc.com) added to the list.

Can someone add it for me, or explain how I would add it?

Thanks.

**Comment by seanmcilvenna** [comment]
Hi Lisa, Can you confirm what screen you are looking at? Perhaps attach a screenshot as well?

**Comment by meenaxigosai** [comment]
Hello Lisa,

Please indicate if you still require assistance with this issue.  If so, please provide the requested information and we will be happy to investigate further.

Best Regards,

Meenaxi

**Comment by LisaRNelson** [comment]
Hi Meenaxi,

 

Yes, I do still need help with this.  I need to add ADVault as a Code System option when specifying vocabulary constraints.  I couldn’t find a way to add an item to that dropdown list.

 

Can you add them for me using the url rather than OID method of identifying them?  Or, if needed, I can send the OID of the Code System and you could add their name for the CodeSystemName element and their OID for the Code System.  In case you need either of these:

 

OID: 


2.16.840.1.113883.15.15.4

ADVault Interoperability Concepts

 

Urn: ADVaultInc.com

 

Thanks,

 

Lisa

 

Lisa R. Nelson, MS, MBA

401.219.1165

LisaRNelson@cox.net

Rhode Island-EDT

 

 <http://www.lisarnelson.com/> www.LisaRNelson.com

Any views or opinions presented in this email are solely those of the author.

**Comment by meenaxigosai** [comment]
Hello Lisa,

I have added a new Code System named "ADVault Interoperability Concepts" with Identifier "urn:oid:2.16.840.1.113883.15.15.4".    

Please confirm if you can see/use this new code system, and if so, I will close out this issue.

Thank you,

Meenaxi

**Comment by rgeimer** [comment]
No reply in 7 days, so assuming this is resolved. Closing the ticket.
