### ISSUE TITLE
CDA export to word has repeating Codesystems in Code System section

### ISSUE THREAD

**Issue by russellott** [lantanagroup/trifolia#34]
It appears that an extract of a CDA-based guide to word populates the Codesystems table with duplicate rows for code systems.  It appear that it may have one row per code in the value sets referenced within the guide that correspond to that codesystem, but I did not do an exact validation of that.

![trifoliacodesystemsrepeated20170503](https://cloud.githubusercontent.com/assets/23243316/25672843/5e086130-3003-11e7-89ff-4c8824b1eae6.jpg)

**Comment by meenaxigosai** [comment]
Hello Russel,

Thank you for submitting this issue to Lantana.  I have exported the Templates to MS Word for the **Periodontal Attachment** IG, and confirmed your findings.   I have opened a JIRA ticket for our internal process and will provide an update as soon as I have discussed the issue with our engineering team.

Thank you,

Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
 
www.lantanagroup.com
Blog | Twitter | LinkedIn

**Comment by meenaxigosai** [comment]
Hello Russel,

Our engineering department has implemented a resolution for the issue you have reported in the Trifolia development environment and the fix has passed QA testing.  The build containing this fix will be deployed to the Trifolia production environment next week and I will notify you once that is complete.

Thank you for your patience and understanding.

Have a wonderful weekend.

Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST

**Comment by seanmcilvenna** [comment]
Trifolia 4.5.0 has been released. This fix is included in the release. Please re-open the ticket if you encounter further problems related to this issue.
