### ISSUE TITLE
can NOT select valueset

### ISSUE THREAD

**Issue by tcheng-altarum** [lantanagroup/trifolia#35]
Can not assign a valueset to data elements

**Comment by meenaxigosai** [comment]
Hello,

Thank you for submitting this request to Lantana.   

In order for us to investigate further, could you please provide the name and identifier of the template/profile and the element to which you are trying to assign the value set to.

Best Regards,


Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
 
www.lantanagroup.com
Blog | Twitter | LinkedIn

**Comment by tcheng-altarum** [comment]
Try this template: Electronic Fetal Monitor During Delivery. Link:
https://trifolia.lantanagroup.com/TemplateManagement/Edit/II/2.16.840.1.113883.10.14.1.1.10.8/2017-16-07

under value@code to Y/N indicator or any other value set, it wouldn’t allow. This is also true if select other value set. Thanks!

-Thanh

**Comment by meenaxigosai** [comment]
Hello Thanh,

Thank you for providing the template and element.  I just tried and was able to successfully bind a value set to the Electronic Fetal Monitor During Delivery template under value@code element.   

Just wanted to confirm with you that you changed the "Binding Type" to **Value Set** before attempting to select the value set to bind to the @code element?   Please see attached screen shot.

Best Regards,

Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
![github 35 value set binding on electronic fetal monitor during delivery](https://cloud.githubusercontent.com/assets/5806630/25718723/05ddc86a-30bc-11e7-9325-e7d210c255b7.png)

**Comment by tcheng-altarum** [comment]
Hello,

Getting to selection is fine, but after you hit OK, nothing happened. It doesn’t matter what you select, it wouldn’t let you “OK” your choice.
Thanks.

-Thanh

**Comment by meenaxigosai** [comment]
Hello Thanh,

Could you please give me the value set that you are trying to attach to the @code element in the Electronic Fetal Monitor During Delivery template, and I will see if Trifolia allows me to add that value set.

Thank you,

Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
