### ISSUE TITLE
Request acces to QDM Templates for CQL-based HQMF IG

### ISSUE THREAD

**Issue by p9g** [lantanagroup/trifolia#36]
The "request access here" link at https://trifolia.lantanagroup.com/IGManagement/List gives an error for anything I try to request.

I was hoping to access QDM Templates for CQL-based HQMF IG and if available QRDA Category I (V5) counterparts.

**Comment by seanmcilvenna** [comment]
Thanks for letting us know about this issue. We will investigate it. We are getting ready to release 4.5 in the next couple weeks, so I will try to get this fix included in the next release. Until then, I will pass on your request for access to the access manager of that IG, and grant you access if approved.

**Comment by seanmcilvenna** [comment]
p9g, can you shoot me your email address and name in an email to sean.mcilvenna@lantanagroup.com so that I can confirm who it is that would like access to QDM and HQMF?

**Comment by seanmcilvenna** [comment]
Also, can you confirm what level of access you would like? Read only? Edit?
