### ISSUE TITLE
Error occurs when request access to IG

### ISSUE THREAD

**Issue by Llentic** [lantanagroup/trifolia#38]
Hello,
I am trying to send a request access to the implementation guide 'CA-ON CDA' so that I can build templates to nestle under this guide.

However, the Trifolia web page keeps giving me an error to do that.

Can anyone help me to fix this problem?

Thank you,
Lentic

**Comment by seanmcilvenna** [comment]
Very close to when this issue was submitted, we were performing a release/update to version 4.5. Can you confirm if you are still encountering this issue? We specifically tested the request functionality, and it was working at the time.

**Comment by meenaxigosai** [comment]
Hello Lentic,

Our developer has just implemented a fix for this.  Can you please try once more and let me know if you are successful.

Thank you,


Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
 
www.lantanagroup.com
Blog | Twitter | LinkedIn

**Comment by Llentic** [comment]
Ok, sorry I didn't realize that! I just send the request, it works! 

Thank you so much for the quick responding!

**Comment by Llentic** [comment]
Thank you for the quick respond!

I just send my request, it works!

Regards,
Lentic
