### ISSUE TITLE
CCDA IG Request Access fail

### ISSUE THREAD

**Issue by buddyo1md** [lantanagroup/trifolia#39]
Trying to access C-CDA IG. Getting this message: <<<Successfully sent access request for Consolidated CDA Templates for Clinical Notes (US Realm) DSTU R2.1.>>> but not seeing the IG in my list despite what APPEARS to be a successful request?

**Comment by seanmcilvenna** [comment]
Are you referring to the list of IGs in Browse > Implementation Guide? Sending an access request requires the request be approved before you are granted access to the IG.

**Comment by meenaxigosai** [comment]
Hello,

Can you please let me know if you are still having trouble access to the C-CDA IG?  If not, I will close this ticket by EOB on Friday June 16, 2017.

Best Regards,


Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
 
www.lantanagroup.com
Blog | Twitter | LinkedIn

**Comment by buddyo1md** [comment]
I have access. Thanks. I was not aware of the turnaround time and just
needed to be patient. You can close the ticket.

CBO

*Charles B. Owen, M.D.*

*Chief Medical Information Officer - Afoundria*
Charles@Afoundria.com
(512) 949-9052 (c)

*Would you like to test drive ChartPath?*
*Website*: testdrive.afoundria.com
*Username*: BuddyGuest
*Password*: chartpath2016

**Comment by meenaxigosai** [comment]
Thank you for confirming.

Best Regards,

Meenaxi Gosai
