### ISSUE TITLE
Not able to access my previous  Implementation Guides or templates

### ISSUE THREAD

**Issue by tcheng-altarum** [lantanagroup/trifolia#4]
Hi,
I've logged in Trifolia Version 4.2.0, but can not access any previous Implementation Guides or other templates, in fact there is nothing in browser view at all. I also tried to join LCG group, but got: "error occurred while joining group". Please let me know when it will be resolved. Thank you!

**Comment by seanmcilvenna** [comment]
Thank you for reporting this bug. I have identified the problem, and believe I have fixed it. Please confirm if the problem is solved for you now, and close the issue if it is.

**Comment by tcheng-altarum** [comment]
Thanks!
