### ISSUE TITLE
Can NOT expand a sub data element

### ISSUE THREAD

**Issue by tcheng-altarum** [lantanagroup/trifolia#42]
Hi,
We are experiencing a problem with not being able to access a sub data element constraint, but we can see it in the text. The conformance #147 and 153 are under #146. Please attachments. Thanks.
![screen-1](https://user-images.githubusercontent.com/22748371/28383193-a25eb9b6-6c8e-11e7-8474-1240fe2e1b9c.png)
![screen-2](https://user-images.githubusercontent.com/22748371/28383197-a41894ca-6c8e-11e7-941e-a08b9f18f625.png)

**Comment by meenaxigosai** [comment]
Hello,

Thank you for submitting this request.  We are aware of this issue and the problem has been fixed and tested in our Trifolia development environment.  

The updated code that includes the resolution for this issue will be deployed to the Trifolia production environment with the release of version 4.6.0 that is schedule for the end of this week or early next week.

Please let us know if you have further questions,

Thank you,

Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
 
www.lantanagroup.com
Blog | Twitter | LinkedIn

**Comment by meenaxigosai** [comment]
Hello,

I re-ested in https://trifolia.lantanagroup.com on September 8, 2017, and confirmed that the constraints can be expanded for Template US Realm Headerm [https://icHeader.abc].

I will close this ticket at this time.  Please do not hesitate to contact us if you encounter any other issues.

Thank you,

Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
