### ISSUE TITLE
Exporting Advance Directives Templates - Revisions -Companion Templates won't include value set

### ISSUE THREAD

**Issue by LisaRNelson** [lantanagroup/trifolia#44]
I am exporting the Advance Directives Templates - Revisions -Companion Templates IG, and it references one value set 
Obligation or Prohibition Instruction Type 
urn:oid:2.16.840.1.113883.11.20.9.69.7
--
And I can't get it to export when exporting the IG.

Can someone please help me figure out WHY???

Thanks.

**Comment by ajagann1** [comment]
Hi Lisa,

Could you please give a bit more info about what browser you're using, what kind of export you're trying to perform (Word, Native, Templates DSTU, etc.) and what settings you're using for that export?

Thanks!
Arvind Jagannathan

**Comment by LisaRNelson** [comment]
Using Chrome

 

Export to Word

Options are:

 



Value Set options are:



 

Lisa R. Nelson, MS, MBA

401.219.1165

LisaRNelson@cox.net

Rhode Island-EDT

 

 <http://www.lisarnelson.com/> www.LisaRNelson.com

Any views or opinions presented in this email are solely those of the author.

**Comment by ajagann1** [comment]
Hi Lisa,

If you go into the "Value Sets" tab of the export, you'll see a field titled "Maximum Members".  Set that to how many members of the value set you wish to be included with your export and you should be good to go.

Thanks!
Arvind Jagannathan

**Comment by LisaRNelson** [comment]
Arvind, for some weird reason my e-mails to rick and sarah are bouncing back as undeliverable. Can you think of why?  I have tried using multiple e-mails to send them, and regardless which address I use, the message returns a system error and says it is undeliverable.

 

Could there be an issue on your end?

 

Lisa R. Nelson, MS, MBA

401.219.1165

LisaRNelson@cox.net

Rhode Island-EDT

 

 <http://www.lisarnelson.com/> www.LisaRNelson.com

Any views or opinions presented in this email are solely those of the author.

**Comment by minigrrl** [comment]
I did get this email though...

On Nov 11, 2017, at 01:59, LisaRNelson <notifications@github.com<mailto:notifications@github.com>> wrote:

Arvind, for some weird reason my e-mails to rick and sarah are bouncing back as undeliverable. Can you think of why? I have tried using multiple e-mails to send them, and regardless which address I use, the message returns a system error and says it is undeliverable.



Could there be an issue on your end?



Lisa R. Nelson, MS, MBA

401.219.1165

LisaRNelson@cox.net<mailto:LisaRNelson@cox.net>

Rhode Island-EDT



<http://www.lisarnelson.com/> www.LisaRNelson.com<http://www.LisaRNelson.com>

Any views or opinions presented in this email are solely those of the author.

**Comment by EricParapini-Lantanagroup** [comment]
Weird!

Sorry Sarah, I should have checked with you first! Just trying to help after seeing this issue come up multiple times.

Eric Parapini
Lantana Consulting Group
t: 206.858.6980
c: 209.727.2525
Seattle, WA – Pacific Time Zone

**Comment by meenaxigosai** [comment]
Hi Lisa,

I have attached the exported word document that does contain the *Obligation or Prohibition Instruction Type urn:oid:2.16.840.1.113883.11.20.9.69.7* value set.

I believe the issue may have been the export settings when the export was completed.  I will close this issue at this time, but if you continue to have problems with this export please feel free to re-open it.  

Thank you,

Meenaxi Gosai
Technical Analyst
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
 
www.lantanagroup.com
Blog | Twitter | LinkedIn

[Advance Directives Templates - Revisions -Companion Templates.docx](https://github.com/lantanagroup/trifolia/files/1483243/Advance.Directives.Templates.-.Revisions.-Companion.Templates.docx)
