### ISSUE TITLE
Missing value set

### ISSUE THREAD

**Issue by LisaRNelson** [lantanagroup/trifolia#45]
I have an IG that uses value set Obligation or Prohibition Instruction Type (urn:oid:2.16.840.1.113883.11.20.9.69.17). It prints out fine when I export the IG and the constraint was able to find and bind to this value set. However, when I try to do a simple search using the value set name in the Browse Terminology screen, it does not appear.  What am i doing wrong?

**Comment by meenaxigosai** [comment]
Hello Lisa,

I have just tried to access the Value Set in Browse Terminology using both the Identifier and Value Set name and the search resulted in displaying the value set.

I'm sure you have done this, but can you make sure there is no space either before or after the value set name when you enter it into the search box and try again please?

Thank you,

Meenaxi Gosai
Technical Analyst
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST
 
www.lantanagroup.com
Blog | Twitter | LinkedIn

**Comment by LisaRNelson** [comment]
Meenaxi - this is so weird.  I can find it if I leave the search open, get all value sets back and then scroll to it, but I can't search for it.  Even trying just the word "Obligation" and no spaces in front or behind.  Note, I did have to update the oid to 2.16.840.1.113883.11.20.9.69.17.  For some reason the .7 OID was already used or deleted in VSAC ????? Weird also....

**Comment by minigrrl** [comment]
I got a weird thing with a value set search the other day where it looked like I couldn’t find the value set but then I noticed it said I was on, like, page 6 of results (when there was only 1 result). When I clicked on the first page my result magically appeared. Could you check this Lisa? If it is the case it is probably some odd bug. I didn’t raise an issue for it as I thought it was probably something I had done, but if it’s the case with you too, probably a bug... Let us know...

On Jan 19, 2018, at 05:52, LisaRNelson <notifications@github.com<mailto:notifications@github.com>> wrote:


Meenaxi - this is so weird. I can find it if I leave the search open, get all value sets back and then scroll to it, but I can't search for it. Even trying just the word "Obligation" and no spaces in front or behind. Note, I did have to update the oid to 2.16.840.1.113883.11.20.9.69.17. For some reason the .7 OID was already used or deleted in VSAC ????? Weird also....

**Comment by minigrrl** [comment]
I can actually reproduce this issue by searching for “Problem” then scrolling to the last page of results, then searching for Lisa’s value set 2.16.840.1.113883.11.20.9.69.17:

[cid:image001.jpg@01D390EE.65A6E910]

But then if I click on the button that takes you to the first page it magically appears:

[cid:image002.jpg@01D390EE.65A6E910]

I will raise a JIRA issue for this and hopefully this is the same issue that Lisa is having…
