### ISSUE TITLE
Caption autotext populating incorrectly in .DOCX export

### ISSUE THREAD

**Issue by russellott** [lantanagroup/trifolia#48]
Captions being generated through the export to .DOCX format seem to be improperly including a colon and space as part of the "autotext" numbering within a caption.

For example, for a caption such as "Table 1: Orthodontic...", the autotext portion of the caption is being identified as "Table [1: ]Orthodontic..." instead of "Table [1]: Orthodontic".

The net result is if this autotext is updated post-export, the included colon and space are removed, resulting in a caption such as "Table 1Orthodontic".

See example below:

![image](https://user-images.githubusercontent.com/23243316/43288778-ecf552a4-90f6-11e8-86e3-b0eccb8f405b.png)

**Comment by russellott** [comment]
Yeah - that's exactly the change I'd request (moving the colon and the space after it after the field char ending point).  I checked an earlier export from Trifolia (from the Periodontal IG) and it was populating the field characters properly in summer 2017, so I don't know when this problem got introduced.

To check it in MSWord, the easy thing is to mouse over the field and a grey overlay will display indicating what's inside the field. You can also right-click on a field and "toggle field codes" which will replace whatever is currently populated within the field with the field code itself, which should make it obvious what's inside and what's outside the field.

Let me know how I can help.

- Russ

**Comment by seanmcilvenna** [comment]
I'm implementing this change, now.
However, take note that this change will result in the field characters basically representing an empty block.
Example: "Table []1: Some Table"
(where [] representing the field characters)

**Comment by russellott** [comment]
That doesn’t look correct - if it’s trouble to default the field value (e.g., “Table [1]: Some Table”), I’d recommend just not setting a default number (e.g., “Table []: Some Table”), and then users will simply need to SHIFT+a (select the whole document) and press F9 to update all field values, which is what they need to do to update the Tables at the top of the document anyways.

- Russ

**Comment by seanmcilvenna** [comment]
Alrighty. I've got the change implemented. I tested it out and I think it's working like we want.
I've deployed the change to our development environment, here: https://trifolia-dev.lantanagroup.com
It would be great if you could login to the DEV environment and give it a test, as well. If all looks good, then we can close the ticket out. Thanks much!

**Comment by russellott** [comment]
I just tested it in DEV and it looks correct to me.  Thanks!

**Comment by seanmcilvenna** [comment]
This fix has been released to production (https://trifolia.lantanagroup.com) as part of the 5.3.1 update.
