### ISSUE TITLE
Assistance with publishing a FHIR IG in preparation for ballot

### ISSUE THREAD

**Issue by AbdulMalikShakir** [lantanagroup/trifolia#49]
Is there someone that can assist me in publishing an FHIR IG in preparation for the September HL7 ballot. I'm developing the IG in Trifolia. It is still a work in progress. However, I need to get familiar with how to prepare it for publication and inclusion in an HL7 ballot. I've read the documentation and I've done some experimenting on my own. But I don't think I am progressing at the pace I need to to meet the August deadline for ballot content. I have GoToMeeting and can set up a meeting with someone willing to walk me through the procedure. Thanks.

**Comment by seanmcilvenna** [comment]
This appears to be a FHIR IG Publisher question, rather than a Trifolia issue.
You can refer to https://chat.fhir.org/#narrow/stream/99-IG-creation for more assistance in publishing FHIR Implementation Guides.
