### ISSUE TITLE
Bookmarks not being created for Value Sets in .DOCX export

### ISSUE THREAD

**Issue by russellott** [lantanagroup/trifolia#50]
After exporting a CDA-based guide into a .DOCX format, a summary table of "Value Sets In This Guide" is created in Section 6.  Each value set is created with an internal hyperlink to where the Value Set is enumerated within the guide, e.g., #Craniofacial_Anomaly for the "Craniofacial Anomaly" value set.

![image](https://user-images.githubusercontent.com/23243316/43784808-f9b9b9ea-9a32-11e8-833c-16b536ccb87b.png)

Unfortunately the corresponding Bookmarks don't seem to be getting established where the value sets are enumerated. leading those internal hyperlinks both in conformance statements and the Value Set summary in Section 6 to navigate to the top of the file, not the intended location:

![image](https://user-images.githubusercontent.com/23243316/43784631-88e282c4-9a32-11e8-8f7d-6138499dac22.png)

This issue can be corrected by manually establishing the missing Bookmark by using Insert -> Bookmark and then establishing a bookmark with the name "Craniofacial_Anomaly".

It appears this bug was introduced in the 7/25/18 release, as an export from 7/24 has the bookmarks created properly.

**Comment by russellott** [comment]
The fix looks good to me in the development environment.

Thanks for the quick resolution!

**Comment by seanmcilvenna** [comment]
This fix has been released to production (https://trifolia.lantanagroup.com) as part of the 5.3.1 update.
