### ISSUE TITLE
Automated numbering of conformance statements not "restarting at 1" for each template

### ISSUE THREAD

**Issue by russellott** [lantanagroup/trifolia#52]
In the export to *.DOCX format, the MS Word numbering for conformance statements isn't flagged to "start new list" for the first conformance statement associated with each template.

The default values immediately upon export are correct, but if you use F9 to "update autotext" throughout the document, the numbering is re-established as one continuous list throughout the whole document - see below.

![image](https://user-images.githubusercontent.com/23243316/44267956-14f27800-a1fe-11e8-9d69-befe1849c54c.png)

Not an urgent bug, but something I found that I thought you'd want to know about.

**Comment by meenaxigosai** [comment]
Hello Russell,

Thank you for reporting this issue.  Our engineering team will investigate and inform you of our findings.

Best Regards,

Meenaxi Gosai
Technical Analyst 
t: 360-450-0545
Maple Ridge, BC (Pacific Time)

**Comment by meenaxigosai** [comment]
Hello Russell,

We investigated this issue a little further this morning, and unfortunately we were unable to reproduce the issue you have reported.  Below are the steps we used to recreate the scenario.

1. Exported the Orthodontic Attachment IG.docx from Trifolia
2. Confirmed that conformance statement numbering for all templates appeared correct
3. Used CTRL+A to select all text within the entire document
4. Pressed F9 to run the autotext update.   
5. Checked the document and found the conformance statement numbering still appears correct.

Please see the attached IG exported today from Trifolia production and let us know if the steps we used to reproduce the problem were the same steps you followed when you encountered this problem.

[Orthodontic Attachment IG_20180817.docx](https://github.com/lantanagroup/trifolia/files/2298387/Orthodontic.Attachment.IG_20180817.docx)

Also, can you confirm that you are using the autotext update when you have manually added items to the templates within the implementation guide.

Thank you,

Meenaxi Gosai
Technical Analyst
t: 360-450-0545
Maple Ridge, BC (Pacific Time)

**Comment by minigrrl** [comment]
Probably not the issue in this case, but something to be aware of is that if you copy and paste the templates into another Word document they always do that renumbering thing.

**Comment by russellott** [comment]
Yeah - that’s exactly what I did. I cut/pasted the content into another document.

Oh well - I cannot replicate the problem within the base export, so I guess this should be closed if we don’t think finding a way to make this work post cut/paste to a new document is a priority.

- Russ

**Comment by seanmcilvenna** [comment]
I'll attempt to figure it out... but it seems like a pretty edge case, and not sure I'm going to find a solution without consuming a lot of time. Perhaps there is someone that has encountered a similar problem in openxml (and found a solution).

**Comment by minigrrl** [comment]
My solution is to always paste the other content into the export – that’s the only way I’ve found to get around the issue…

**Comment by minigrrl** [comment]
BTW – from my research (a while ago now) it appears to be a Word issue – I don’t think you will be able to fix it from Trifolia. Would love to be proven wrong though! 😊
