### ISSUE TITLE
Need to support the HQMF Normative R1 schema

### ISSUE THREAD

**Issue by yanheras** [lantanagroup/trifolia#53]
Trifolia currently does not support the schema for the HL7 Version 3 Standard: Representation of the Health Quality Measure Format (eMeasure) Release 1 (http://www.hl7.org/documentcenter/private/standards/v3/HL7_V3_HQMF_R1_2017JUN_2017OCT_Errata.zip). Since the latest CQL-based HQMF IG is based on the HQMF Normative R1, some new attributes added to the R1 are not supported in Trifolia, and therefore, cannot be edited through Trifolia.

**Comment by meenaxigosai** [comment]
Hello Yan,

Thank you for bringing this issue to our attention.   We will be working on updating the schema next week, and will inform you when the fix has been released to production.

Thank you, and have a great weekend!

Meenaxi Gosai
Technical Analyst 
t: 360-450-0545
Maple Ridge, BC (Pacific Time)

**Comment by seanmcilvenna** [comment]
Hi Yan,
I just released an update to Trifolia (5.3.2) that includes the latest HQMF R2 schema from 2017.
Thank you

**Comment by yanheras** [comment]
Hi Sean,

 

Thank you for including the HQMF R2 schema!

 

Can the existing IGs in Trifolia safely be converted using the new schema? For example, all existing constraints will not be affected. Or, switching to use the new schema can only be done when crate future new version of the existing IGs?

 

Thanks,

Yan

**Comment by seanmcilvenna** [comment]
The template editor will automatically pick up the changes to the schema, but will *not* automatically update any constraints. The constraints that exist now, will stay as they are. However, if the constraints are targeting elements/attributes that no longer exist in the updated schema, it will show those constraints in red, indicating that they should be changed.

Thanks,

Sean McIlvenna
t: 208.930.0350
Idaho – PDT (UTC -08:00)

**Comment by yanheras** [comment]
Thank you Sean!

**Comment by seanmcilvenna** [comment]
You’re welcome!

Sean McIlvenna
t: 208.930.0350
Idaho – PDT (UTC -08:00)
