### ISSUE TITLE
reference element under originalText is of dataType TEL - why???

### ISSUE THREAD

**Issue by LisaRNelson** [lantanagroup/trifolia#55]
Why would the data type of the reference element under originalText be of type TEL?  We use this to reference the narrative text associated with the originalText.  Reference holds a value that dereferences the narrative using and id in the section.text.

**Comment by meenaxigosai** [comment]
Hello Lisa,

I understand that you have already discussed this issue with Sarah Gaunt and she has provided an explanation of the dataType TEL.   I will close this ticket at this time.

If you have further questions or concerns, please feel free to contact our team via the JIRA service desk.

Best Regards,

Meenaxi Gosai
Technical Analyst
Lantana Consulting Group
t: 360-450-0545
Maple Ridge, BC (Pacific Time)
