### ISSUE TITLE
Add fields to hold IG-specific implementation instructions

### ISSUE THREAD

**Issue by minigrrl** [lantanagroup/trifolia#7]
Modification to Trifolia to add a field to each template (and ideally each constraint) that would be IG specific and could hold IG-specific implementation instructions.

This would be specifically for the HIT Pharmacy project, but would benefit other projects as well.

What happens now, is that if we feel implementation instructions for a particular IG are important enough, we will create a new template based on the old template and not make any changes to constraints in the template, but add extra implementation instructions.

A template-level field that is owned by the IG, not the template, would allow us to add instructions that only get printed out with the IG when that template is exported with the particular IG.

Constraint-level fields would be the same.  This would mean we could map IG (client/user) specific fields to elements in the template.  Or give further instructions about how to use that element in this particular use case.

This would be SUPER useful!

**Comment by meenaxigosai** [comment]
Hello @minigrrl ,

I have created https://trifolia.atlassian.net/browse/TRIF-1357 to track this issue and will close out this GITHUB ticket.

Best Regards,

Meenaxi Gosai
